import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { z } from 'zod';

// ============================================
// GET /api/v1/bookings - List all bookings
// ============================================
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { searchParams } = new URL(request.url);

    // Params
    const status = searchParams.get('status');
    const search = searchParams.get('search');
    const date_from = searchParams.get('date_from');
    const date_to = searchParams.get('date_to');
    const page = parseInt(searchParams.get('page') || '1', 10);
    const limit = parseInt(searchParams.get('limit') || '50', 10);
    const offset = (page - 1) * limit;

    // Query with relations
    let query = supabase
      .from('bookings')
      .select(`
        *,
        category:service_categories(id, name_de, name_en, slug),
        brand:brands(id, name),
        model:models(id, name),
        service:services(id, name_de, name_en, slug),
        assigned_to:users(id, full_name, email)
      `, { count: 'exact' });

    // Filters
    if (status && status !== 'all') {
      query = query.eq('status', status);
    }

    if (search && search.trim()) {
      query = query.or(`booking_number.ilike.%${search.trim()}%,customer_name.ilike.%${search.trim()}%,customer_email.ilike.%${search.trim()}%,customer_phone.ilike.%${search.trim()}%`);
    }

    if (date_from) {
      query = query.gte('created_at', date_from);
    }

    if (date_to) {
      query = query.lte('created_at', date_to);
    }

    // Order by newest first
    query = query.order('created_at', { ascending: false });

    // Pagination
    query = query.range(offset, offset + limit - 1);

    const { data, error, count } = await query;

    if (error) {
      console.error('Bookings fetch error:', error);
      return NextResponse.json(
        { success: false, error: { message: error.message } },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      data: {
        items: data || [],
        total: count || 0,
        page,
        limit,
      },
    });
  } catch (error) {
    console.error('Unexpected error:', error);
    return NextResponse.json(
      { success: false, error: { message: 'Server xətası' } },
      { status: 500 }
    );
  }
}

// ============================================
// POST /api/v1/bookings - Create new booking
// ============================================
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const body = await request.json();

    // Validation
    const bookingSchema = z.object({
      customer_name: z.string().min(2, 'Ad ən azı 2 simvol olmalıdır').max(255),
      customer_email: z.string().email('Yanlış e-poçt').optional().or(z.literal('')),
      customer_phone: z.string().min(5, 'Telefon ən azı 5 simvol olmalıdır').max(50),
      customer_whatsapp: z.string().max(50).optional().or(z.literal('')),
      category_id: z.string().uuid().optional().nullable(),
      brand_id: z.string().uuid().optional().nullable(),
      model_id: z.string().uuid().optional().nullable(),
      service_id: z.string().uuid().optional().nullable(),
      status: z.enum(['pending', 'confirmed', 'in_progress', 'completed', 'cancelled']).default('pending'),
      estimated_price: z.string().max(50).optional().or(z.literal('')),
      final_price: z.number().optional().nullable(),
      booking_date: z.string().optional().nullable(),
      customer_notes: z.string().optional().or(z.literal('')),
      internal_notes: z.string().optional().or(z.literal('')),
      assigned_to: z.string().uuid().optional().nullable(),
      source: z.string().max(50).default('website'),
    });

    const validatedData = bookingSchema.parse(body);

    // Insert (booking_number will be auto-generated by trigger)
    const { data, error } = await supabase
      .from('bookings')
      .insert([{
        customer_name: validatedData.customer_name,
        customer_email: validatedData.customer_email || null,
        customer_phone: validatedData.customer_phone,
        customer_whatsapp: validatedData.customer_whatsapp || null,
        category_id: validatedData.category_id || null,
        brand_id: validatedData.brand_id || null,
        model_id: validatedData.model_id || null,
        service_id: validatedData.service_id || null,
        status: validatedData.status,
        estimated_price: validatedData.estimated_price || null,
        final_price: validatedData.final_price || null,
        booking_date: validatedData.booking_date || null,
        customer_notes: validatedData.customer_notes || null,
        internal_notes: validatedData.internal_notes || null,
        assigned_to: validatedData.assigned_to || null,
        source: validatedData.source,
      }])
      .select()
      .single();

    if (error) {
      console.error('Booking insert error:', error);
      return NextResponse.json(
        { success: false, error: { message: error.message } },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, data }, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { success: false, error: { message: error.errors[0].message } },
        { status: 400 }
      );
    }

    console.error('Unexpected error:', error);
    return NextResponse.json(
      { success: false, error: { message: 'Server xətası' } },
      { status: 500 }
    );
  }
}
